### ISSUE TITLE
OpenGL 1282 error

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#171] opened 2018-05-20 22:33 UTC
This is a new one that I got when volume rendering a generative image (in fun.imagej + sciview). It could have been something crazy in the image that wasn't safely checked, so I'm just saving this as a note.

```
Exception in thread "SciJava-321fc753-Thread-4-FPSAWTAnimator#00-Timer0" com.jogamp.opengl.util.AnimatorBase$UncaughtAnimatorException: com.jogamp.opengl.GLException: Caught Exception: OpenGL error: 1282 on thread SciJava-321fc753-Thread-4-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:92)
	at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
	at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.jogamp.opengl.GLException: Caught Exception: OpenGL error: 1282 on thread SciJava-321fc753-Thread-4-FPSAWTAnimator#00-Timer0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at jogamp.opengl.GLAutoDrawableBase.defaultDisplay(GLAutoDrawableBase.java:476)
	at com.jogamp.opengl.GLAutoDrawableDelegate.display(GLAutoDrawableDelegate.java:190)
	at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
	... 4 more
Caused by: java.lang.Exception: OpenGL error: 1282
	at graphics.scenery.backends.opengl.OpenGLRenderer.render(OpenGLRenderer.kt:1326)
	at graphics.scenery.backends.opengl.OpenGLRenderer.display(OpenGLRenderer.kt:633)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	... 8 more
```

**Comment by skalarproduktraum** [comment] 2018-05-22 20:36
Could you please run the code with `-Djogl.debug.DebugGL=true`? This'll emit the error at the place where it is raised.

**Comment by skalarproduktraum** [comment] 2018-06-01 12:18
So this does just happen when taking screenshot? Or what are the preceding operations?

**Comment by skalarproduktraum** [comment] 2018-06-01 17:34
Okay, this seems to be a duplicate of #174, closing therefore.

**Closed by skalarproduktraum** 2018-06-01 17:34 UTC
Labels: duplicate
