### ISSUE TITLE
Cylinder returning OrientedBoundingBox with NaN's

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#308] opened 2020-05-05 01:59 UTC
I'm using this method (https://github.com/scenerygraphics/sciview/blob/master/src/main/java/sc/iview/SciView.java#L646) on neuron traces from SNT. All cylinders are created the same way except their lengths. Here is some example output: in debug I inspected these cylinders and their attributes are totally normal. It isn't clear to me what the issue is with these BBs. 

```
...
GSBB: ( 8.488E+1  1.223E+2 -2.500E-1) ( 8.488E+1  1.223E+2 -2.500E-1) sphere
GSBB: (NaN NaN NaN) (NaN NaN NaN) cylinder
GSBB: ( 8.488E+1  1.223E+2 -2.500E-1) ( 8.488E+1  1.223E+2 -2.500E-1) sphere
GSBB: (NaN NaN NaN) (NaN NaN NaN) cylinder
GSBB: ( 8.488E+1  1.223E+2 -2.500E-1) ( 8.488E+1  1.223E+2 -2.500E-1) sphere
GSBB: ( 8.512E+1  1.223E+2 -2.486E-1) ( 8.512E+1  1.223E+2 -2.486E-1) cylinder
GSBB: ( 8.388E+1  1.223E+2 -2.500E-1) ( 8.388E+1  1.223E+2 -2.500E-1) sphere
GSBB: ( 8.412E+1  1.223E+2 -2.486E-1) ( 8.412E+1  1.223E+2 -2.486E-1) cylinder
GSBB: ( 8.288E+1  1.223E+2 -2.500E-1) ( 8.288E+1  1.223E+2 -2.500E-1) sphere
GSBB: ( 8.312E+1  1.223E+2 -2.486E-1) ( 8.312E+1  1.223E+2 -2.486E-1) cylinder
...
```

Note: this only happens for some Cylinder's not all

**Comment by skalarproduktraum** [comment] 2020-08-11 08:48
Can't reproduce this issue, I even tried creating cylinders with zero radius, length, or segments. Could you check if the cylinders you create there are somehow weird?

**Comment by skalarproduktraum** [comment] 2021-02-26 11:35
Closing because couldn't be reproduced. Please reopen if it occurs again.

**Closed by skalarproduktraum** 2021-02-26 11:35 UTC
Labels: needs-verification
