### ISSUE TITLE
Java examples dot not run if a logging mechanism is not on the classpath.

### ISSUE THREAD

**Issue by tinevez** [scenerygraphics/scenery#119] opened 2017-12-04 17:50 UTC
When consuming scenery as a library, and copy/pasting the java simple example (https://github.com/scenerygraphics/scenery/blob/master/src/test/tests/graphics/scenery/tests/examples/basic/TexturedCubeJavaExample.java), the later does not run, lest a logging artifact is on the classpath.

Adding _e.g._
```
	<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-simple</artifactId>
	<version>1.7.25</version>
	</dependency>
```
to the `pom` file fixes the issue.

**Comment by skalarproduktraum** [comment] 2017-12-05 16:48
Can't reproduce this at the moment, but both the order in which SceneryBase expects things to be called and the use of a slf4j binding should be documented better. Thanks for the report, @tinevez !

**Comment by skalarproduktraum** [comment] 2018-01-17 16:21
I'll close this for the moment as I could not reproduce this further. If I remember correctly, this was ultimately related to an issue with the graphics driver. If you think this is an error, @tinevez, please feel free to reopen!

**Closed by skalarproduktraum** 2018-01-17 16:21 UTC
Labels: documentation, needs-verification
