### ISSUE TITLE
Race conditions in Vulkan?

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#191] opened 2018-06-28 08:04 UTC
Vulkan fails to start with these as the last messages. By fails to start I mean that when opening SciView the render output never shows up. However, this only works when log level is info. When log level is debug the startup time is a bit slower, hence the suspicion of a race condition. 
[ Note that this doesn't always happen, but it is repeatable ]

```
[SciJava-cfff6af-Thread-1] INFO VulkanRenderer - Recreating Swapchain at frame 0
[SciJava-cfff6af-Thread-1] INFO FXSwapchain - Created 2 swapchain images
```

```
[SciJava-2a073cbf-Thread-1] INFO VulkanRenderer - Recreating Swapchain at frame 0
[SciJava-2a073cbf-Thread-1] ERROR VulkanRenderer - Call to allocate image staging memory of size 1920000 failed: A device memory allocation has failed.
```

A related observation, sometimes when attempting to open volumes in Vulkan, they never show up (but other elements of the scene do show up).

**Comment by skalarproduktraum** [comment] 2018-06-28 11:38
Slightly strange... what version of Nvidia's driver are you using? And could you try running this with validation layers enabled (with Vulkan SDK installed, run scenery/sciview with `-Dscenery.VulkanRenderer.EnableValidations=true`)?

**Comment by skalarproduktraum** [comment] 2018-08-20 15:49
Any more info on this, @kephale? Otherwise I'll close this because I cannot reproduce it.

**Comment by kephale** [comment] 2018-08-20 16:08
I haven't seen this in a while, but I've added an unsightly amount of `Thread.sleep` calls to my scripts. IMHO there is still a notable design issue that needs to be addressed with the async implementation relative to user expectations of synchronous control. The most common glaring example of this is the need to use Thread.sleep when doing screenshots and such. I believe that this is the sort of issue that is traditionally solved with a scheduler.

**Comment by skalarproduktraum** [comment] 2019-05-24 12:19
As there's no more information on this. I'll close it for the moment. Feel free to reopen in case this still occurs.

**Closed by skalarproduktraum** 2019-05-24 12:19 UTC
Labels: needs-verification
