### ISSUE TITLE
Freezing with Vulkan on Ubuntu 18.04

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/scenery#303] opened 2020-04-08 13:01 UTC
I observed freezing of scenery renders, particularly when interacting with window decorations. Long freezes of 30s-1m with brief bursts of render output. The same behavior was observed with `vkcube`. We investigated vsync and PRESENT modes to no avail. 

We (w/ @skalarproduktraum ) solved this by disabling animations in gnome (which is `on` by default) resolved the issue. https://wiki.gnome.org/action/show/Apps/Tweaks?action=show&redirect=Apps%2FGnomeTweakTool

Gnome version: 3.22+9 
NVIDIA-SMI 440.64.00
Quadro P2000

**Comment by skalarproduktraum** [comment] 2020-04-08 13:02
So this issue probably is an upstream issue, as it also occurs with the `vkcube` SDK sample. Nevertheless tracking it here before somebody forgets 👍

**Comment by skalarproduktraum** [comment] 2020-04-08 13:03
Also for the record, this is not reproducible on ArchLinux with Gnome 3.36, with 440.82 Nvidia drivers on a GTX1070.

**Comment by skalarproduktraum** [comment] 2020-04-23 17:42
We finally succeeded to trace this to the animation engine of GNOME 3.22+9. When deactivating animations, Vulkan applications work as intended. Closing because not a scenery issue.

**Closed by skalarproduktraum** 2020-04-23 17:42 UTC
Labels: needs-verification, upstream-library
